# Generated by Django 5.2.6 on 2026-03-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
